parameters:
  - name: environmentName
    type: string
  - name: serviceName
    type: string
  - name: locationCode
    type: string    
jobs:
  - job: plan_${{ parameters.serviceName }}_${{ parameters.locationCode }}_${{ parameters.environmentName }}
    variables:
      - template: ../variables/${{ parameters.environmentName }}.job.vars.yml
    steps:
      # check code is formatted correctly
      - template: ../tasks/terraform_fmt_task.yml
      # update Terraform version if required
      - template: ../tasks/apt_installterraform_task.yml      
      # fetch credentials from Az CLI into environment vars          
      - template: ../tasks/terraform_creds_task.yml
        parameters:
          AzureRMServiceConnection: ${{ variables.AzureRMServiceConnection}}
      # terraform init
      - template: ../tasks/terraform_init_azurebackend_task.yml
        parameters:
          tfstateResourceGroupName: ${{ variables.tfstateResourceGroupName}}
          tfstateStorageAccountName: ${{ variables.tfstateStorageAccountName}}
          tfstateStorageContainerName: ${{ variables.tfstateStorageContainerName}}
      # terraform validate
      - template: ../tasks/terraform_validate_task.yml
      # terraform plan
      - template: ../tasks/terraform_plan_task.yml
        parameters:
          environmentTFVARS: ${{ variables.environmentTFVARS}}