parameters:
  - name: environmentName
    type: string
  - name: serviceName
    type: string
  - name: locationCode
    type: string    
jobs:
  - job: plan_${{ parameters.serviceName }}_${{ parameters.locationCode }}_${{ parameters.environmentName }}
    variables:
      - template: ../variables/${{ parameters.environmentName }}.job.vars.yml
    steps:
      - template: ../tasks/terraform_fmt_task.yml
        parameters:
          azureSubscriptionName: ${{ variables.AzureRMServiceConnection}}
      - template: ../tasks/terraform_create_azurebackend_task.yml
        parameters:
          azureSubscriptionName: ${{ variables.AzureRMServiceConnection}}
          resourceGroupName: ${{ variables.tfstateResourceGroupName}}
          storageAccountName: ${{ variables.tfstateStorageAccountName}}
          tfstateContainer: ${{ variables.tfstateStorageContainerName}}
          location: ${{ variables.location}}
      - template: ../tasks/terraform_init_azurebackend_task.yml
        parameters:
          azureSubscriptionName: ${{ variables.AzureRMServiceConnection}}
          resourceGroupName: ${{ variables.tfstateResourceGroupName}}
          storageAccountName: ${{ variables.tfstateStorageAccountName}}
          tfstateContainer: ${{ variables.tfstateStorageContainerName}}
