parameters:
  - name: environmentName
    type: string
  - name: serviceName
    type: string
  - name: locationCode
    type: string    
jobs:
  - job: plan_${{ parameters.serviceName }}_${{ parameters.locationCode }}_${{ parameters.environmentName }}
    variables:
      - template: ../variables/${{ parameters.environmentName }}.job.vars.yml
    steps:
      # check code is formatted correctly
      - template: ../tasks/terraform_fmt_task.yml
      # create terraform storage container if not already there
      - template: ../tasks/terraform_create_azurebackend_task.yml      
        parameters:
          azureSubscriptionName: ${{ variables.AzureRMServiceConnection}}
          tfstateResourceGroupName: ${{ variables.tfstateResourceGroupName}}
          tfstateStorageAccountName: ${{ variables.tfstateStorageAccountName}}
          tfstateStorageContainerName: ${{ variables.tfstateStorageContainerName}}
          tfstateLocation: ${{ variables.tfstateLocation}}
      # fetch credentials from Az CLI into environment vars          
      - template: ../tasks/terraform_creds_task.yml
        parameters:
          azureSubscriptionName: ${{ variables.AzureRMServiceConnection}}
      # terraform init          
      - template: ../tasks/terraform_init_azurebackend_task.yml
        parameters:
          tfstateResourceGroupName: ${{ variables.tfstateResourceGroupName}}
          tfstateStorageAccountName: ${{ variables.tfstateStorageAccountName}}
          tfstateStorageContainerName: ${{ variables.tfstateStorageContainerName}}
