parameters:
  - name: environmentObjects
    type: object
  - name: serviceName
    type: string

stages:
  - stage: "${{ parameters.serviceName }}_plan"
    displayName: Terraform Plan  
    jobs:
      - ${{ each environmentObject in parameters.environmentObjects }}:
          - ${{ each locationCode in environmentObject.locationCode }}:
              - template: ../jobs/terraform_plan_job.yml
                parameters:
                  environmentName: ${{ environmentObject.environmentName }}
                  serviceName: ${{ parameters.serviceName }}
                  locationCode: ${{ locationCode }}
