parameters:
  - name: environmentObjects
    type: object
  - name: serviceName
    type: string

stages:
  - ${{ each environmentObject in parameters.environmentObjects }}:
      - ${{ each locationCode in environmentObject.locationCode }}:
          - stage: apply_${{ parameters.serviceName }}_${{ locationCode }}_${{ environmentObject.environmentName }}
            displayName: Terraform Apply (${{ locationCode }} - ${{ environmentObject.environmentName }})
            # only allowed to run (following approval) if terraform plan succeeded.
            dependsOn: plan_${{ parameters.serviceName }}_${{ locationCode }}_${{ environmentObject.environmentName }}
            # do not run Terrform Apply if plan fails
            condition: succeeded() #and(succeeded(), eq(variables['terraform_pending_changes'],'true'))
            jobs:
              - template: ../jobs/terraform_apply_job.yml
                parameters:
                  environmentName: ${{ environmentObject.environmentName }}
                  serviceName: ${{ parameters.serviceName }}
                  locationCode: ${{ locationCode }}
