parameters:
  - name: environmentObjects
    type: object
  - name: serviceName
    type: string

stages:
  - stage: "${{ parameters.serviceName }}_plan"
    jobs:
      - ${{ each environmentObject in parameters.environmentObjects }}:
          - template: ../jobs/terraform_plan_job.yml
            parameters:
              environmentName: ${{ environmentObject.environmentName }}
              serviceName: ${{ parameters.serviceName }}
              locationCode: ${{ environmentObject.locationCode }}
