parameters:
  - name: environmentObjects
    type: object
  - name: serviceName
    type: string

stages:
  - ${{ each environmentObject in parameters.environmentObjects }}:
      - ${{ each locationCode in environmentObject.locationCode }}:
          - stage: plan_${{ parameters.serviceName }}_${{ locationCode }}_${{ environmentObject.environmentName }}
            displayName: Terraform Plan ${{ locationCode }} ${{ environmentObject.environmentName }}
            dependsOn: []
            jobs:
              - template: ../jobs/terraform_plan_job.yml
                parameters:
                  environmentName: ${{ environmentObject.environmentName }}
                  serviceName: ${{ parameters.serviceName }}
                  locationCode: ${{ locationCode }}
