parameters:
  - name: environmentObjects
    type: object
  - name: serviceName
    type: string

stages:
  - stage: "${{ parameters.serviceName }}_apply"
    displayName: Terraform Apply
    # only allowed to run (following approval) if terraform plan succeeded.
    dependsOn: ${{ parameters.serviceName }}_plan
    # do not run Terrform Apply if plan fails
    condition: succeeded() # and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'],'true'))
    jobs:
      - ${{ each environmentObject in parameters.environmentObjects }}:
          - ${{ each locationCode in environmentObject.locationCode }}:
              - template: ../jobs/terraform_apply_job.yml
                parameters:
                  environmentName: ${{ environmentObject.environmentName }}
                  serviceName: ${{ parameters.serviceName }}
                  locationCode: ${{ locationCode }}