steps:
  - bash: |
      echo 'Checking Terraform version'
      terraform --version

      tfoutofdate=$(terraform --version | grep -c 'out of date')

      if [[ $tfoutofdate -ne 0 ]]; then
        echo 'Terraform out of date. Updating to latest'
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install terraform
        sudo rm -rf /usr/local/bin/terraform
        sudo cp -p /usr/bin/terraform /usr/local/bin/terraform
        terraform -version
      fi

    displayName: Update Terraform if required
    workingDirectory: ${{ parameters.workingDirectory }}
