parameters:
  - name: azureSubscriptionName
    type: string
  - name: resourceGroupName
    type: string
  - name: storageAccountName
    type: string
  - name: tfstateContainer
    type: string

steps:
  # Set AzureRM credentials to environment variables using Terraform's convention.
  # https://www.terraform.io/language/settings/backends/azurerm
  - task: AzureCLI@2
    displayName: Set ARM environment variables
    inputs:
      azureSubscription: ${{ parameters.azureSubscriptionName }}
      scriptType: "pscore"
      # this is required so that the service principal details are available
      addSpnToEnvironment: $true
      scriptLocation: "inlineScript"
      inlineScript: |
          Write-Host "Setting Terraform environment variables for Azure RM"
          $subscriptionId = (Get-AzContext).Subscription.Id
          echo "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$env:servicePrincipalKey"
