parameters:
  - name: workingDirectory
    type: string
    default: $(Build.SourcesDirectory)

steps:
  # check terraform code is valid prior to plan
  - pwsh: terraform validate
    displayName: Terraform Validate
    workingDirectory: ${{ parameters.workingDirectory }}