parameters:
  - name: resourceGroupName
    type: string
  - name: storageAccountName
    type: string
  - name: tfstateContainer
    type: string

steps:
  - bash: |
      printenv | sort
      terraform init -reconfigure \
        -backend-config="container_name=${{ parameters.tfstateContainer }}" \
        -backend-config="storage_account_name=${{ parameters.storageAccountName }}" \
        -backend-config="resource_group_name=${{ parameters.resourceGroupName }}"
    displayName: Terraform Init
    workingDirectory: $(Build.SourcesDirectory)
