parameters:
  - name: environmentTFVARS
    type: string
  - name: workingDirectory
    type: string
    default: '$(Pipeline.Workspace)'

steps:
  # Run terraform plan (output to tfplan) & finally terraform apply to deploy the infrastructure changes
  - pwsh: |
      terraform apply -auto-approve -input=false tfplan
    displayName: Terraform Apply
    workingDirectory: ${{ parameters.workingDirectory }}