parameters:
  - name: azureSubscriptionName
    type: string

steps:
  # Set AzureRM credentials to environment variables using Terraform's convention.
  # https://www.terraform.io/language/settings/backends/azurerm
  - task: AzureCLI@2
    displayName: Set ARM environment variables
    inputs:
      azureSubscription: ${{ parameters.azureSubscriptionName }}
      scriptType: "pscore"
      # this is required so that the service principal details are available
      addSpnToEnvironment: true
      scriptLocation: "inlineScript"
      inlineScript: |
          Write-Host "Setting Terraform environment variables for Azure RM"
          $subscriptionId = az account show --query id --output tsv
          Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
          Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
          Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
          Write-Host "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$env:servicePrincipalKey"
          Write-Host "Tenant Id: " $env:tenantId
          Write-Host "Service Principal Id: " $env:servicePrincipalId
          Write-Host "Service Principal Key is null: " $($null -eq $env:servicePrincipalKey )