parameters:
  - name: azureSubscriptionName
    type: string
  - name: resourceGroupName
    type: string
  - name: storageAccountName
    type: string
  - name: tfstateContainer
    type: string

steps:
  - task: AzureCLI@2
    displayName: Terraform init backend
    inputs:
      azureSubscription: ${{ parameters.azureSubscriptionName }}
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        terraform init -reconfigure `
          -backend-config="container_name=${{ parameters.tfstateContainer }}" `
          -backend-config="storage_account_name=${{ parameters.storageAccountName }}" `
          -backend-config="resource_group_name=${{ parameters.resourceGroupName }}"
