parameters:
  - name: environmentTFVARS
    type: string

steps:
  # Terraform Plan - output changes to be made to the console for review
  # TODO if we output to json is that then comparable?
  - pwsh: |
      if ($env:ARM_USE_OIDC) {
        if ($null -eq $env:ARM_OIDC_TOKEN -or "" -eq $env:ARM_OIDC_TOKEN) {
          Write-Error "Auth token is null or empty, can not continue."
          exit 1
        }
        # ARM_CLIENT_SECRET must not be set if using OIDC.
        Remove-Item env:ARM_CLIENT_SECRET
      }

      Write-Host 'Running terraform plan'
      terraform plan -input=false -out=$(Build.ArtifactStagingDirectory)/tfplan `
          -var-file='${{ parameters.environmentTFVARS }}' `
          -detailed-exitcode

      switch ($lastExitCode) {
          0 {
              Write-Host 'No changes to infrastructure detected.'
              Write-Host "##vso[task.setvariable variable=terraform_pending_changes;isOutput=true]$true"              
              exit 0
          }
          1 { 
              Write-Host 'Terraform plan failed.'
              Write-Host "##vso[task.setvariable variable=terraform_pending_changes;isOutput=true]$true"              
              exit 1 
          }
          2 {
              Write-Host 'Changes to infrastructure are required.'
              Write-Host "##vso[task.setvariable variable=terraform_pending_changes;isOutput=true]$true"
              exit 0
          }
      }
    displayName: Terraform Plan
    workingDirectory: $(Build.SourcesDirectory)
    env:
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_OIDC_TOKEN: $(ARM_OIDC_TOKEN)

    # copy the terraform code and tfplan
  - task: CopyFiles@2
    displayName: Copy files to artifact directory
    inputs:
        SourceFolder: "$(Build.SourcesDirectory)"
        Contents: |
            **/*
            !.git/**/*
            !.terraform/**/*
            !.vscode/**/*
            !.gitignore
            !.terraform.lock.hcl
            !README.md
            !docs/**/*
            !helpers/**/*
        TargetFolder: "$(Build.ArtifactStagingDirectory)"

    # publish the plan to the pipeline
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact: terraform code'
    inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: terraform
