parameters:
  - name: environmentTFVARS
    type: string
  - name: workingDirectory
    type: string
    default: '$(Pipeline.Workspace)'

steps:
  # Run terraform plan (output to tfplan) & finally terraform apply to deploy the infrastructure changes
  - pwsh: |
      if ($env:ARM_USE_OIDC) {
        if ($null -eq $env:ARM_OIDC_TOKEN -or "" -eq $env:ARM_OIDC_TOKEN) {
          Write-Error "Auth token is null or empty, can not continue."
          exit 1
        }
        # ARM_CLIENT_SECRET must not be set if using OIDC.
        Remove-Item env:ARM_CLIENT_SECRET
      }
      Write-Host "Running Terraform Apply."
      terraform apply -auto-approve -input=false tfplan
    displayName: Terraform Apply
    workingDirectory: ${{ parameters.workingDirectory }}
    env:
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_OIDC_TOKEN: $(ARM_OIDC_TOKEN)    