parameters:
  - name: environmentObjects
    type: object
    default:
      - environmentName: "dev"
        location: ["AustraliaEast"]
        locationCode: ["auea"]

      - environmentName: "tst"
        location: ["AustraliaEast", "AustraliaSouthEast"]
        locationCode: ["auea", "ause"]

  - name: serviceName
    type: string
    default: "terraform"

stages:
  - template: stages/terraform_plan_stage.yml
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      serviceName: ${{ parameters.serviceName }}

  - template: stages/terraform_apply_stage.yml      
    parameters:  
      environmentObjects: ${{ parameters.environmentObjects }}
      serviceName: ${{ parameters.serviceName }}
