trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

# resources:
#   repositories:
#   - repository: YAMLTemplates
#     type: git
#     name: Examples/YAMLTemplates

stages:
  - template: terraform.template.yml
    parameters:
      environmentObjects:
        - environmentName: "dev"
          location: ["AustraliaEast"]
          locationCode: ["auea"]
