trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: terraform.template.yml
    parameters:
      environmentObjects:
        - environmentName: "dev"
          location: ["AustraliaEast"]
          locationCode: ["auea"]
