trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: terraform.template.yml
    parameters:
      environmentObjects:
        - environmentName: "dev"
          locationCode: ["auea"]

        - environmentName: "tst"
          locationCode: ["auea"]

  # code should be checked into the 'main' branch to go to production
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
      - template: terraform.template.yml
        parameters:
          environmentObjects:
            - environmentName: "prd"
              locationCode: ["auea"]
