parameters:
  - name: environmentObjects
    type: object
  - name: serviceName
    type: string

stages:
  - template: stages/terraform_plan_stage.yml
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      serviceName: ${{ parameters.serviceName }}

  - template: stages/terraform_apply_stage.yml      
    parameters:  
      environmentObjects: ${{ parameters.environmentObjects }}
      serviceName: ${{ parameters.serviceName }}
