trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: terraform.template.yml
    parameters:
      environmentObjects:
        - environmentName: "dev"
          location: ["AustraliaEast"]
          locationCode: ["auea"]

  - template: terraform.template.yml
    parameters:
      environmentObjects:
        - environmentName: "tst"
          location: ["AustraliaEast"]
          locationCode: ["auea"]

        - environmentName: "tst"
          location: ["AustraliaSouthEast"]
          locationCode: ["ause"]
